# 单数据源配置 mysql8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: never
    # druid 配置
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      #filters: conn,config,stat,slf4j
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          # 输出可执行 sql 日志
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
          statement-sql-pretty-format: true

  # jpa 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081

logging:
  level:
    druid:
      sql:
        Statement: debug
