# 多数据源配置
foo:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

bar:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081