management:
  endpoints:
    web:
      exposure:
        include: "*"

######################### Eureka #############################################

eureka:
  client:
    serviceUrl:
      # 这个是默认配置，可以不用写的
      defaultZone: http://localhost:8761/eureka/
  instance:

    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

server:
  port: 8080
